apiVersion: v1
description: minotar.net Website
name: minotar-website
version: 1.0.0
appVersion: 1.0.0
home: https://minotar.net/
sources:
  - https://github.com/minotar/minotar.net
keywords:
  - minotar
maintainers:
  - name: LukeH
