
redis:
  configmap: |
    maxmemory 500M
    maxmemory-policy volatile-lfu
    cluster-require-full-coverage no
    cluster-allow-reads-when-down yes

  ## Redis(TM) resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 100m
      memory: 700Mi
    requests:
      cpu: 10m
      memory: 500Mi

## Prometheus Exporter / Metrics
##
metrics:
  ## Custom PrometheusRule to be defined
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  ## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
  ##
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ""
    rules: []
    ## These are just examples rules, please adapt them to your needs.
    ## Make sure to constraint the rules to the current postgresql service.
    #  - alert: RedisDown
    #    expr: redis_up{service="{{ template "common.names.fullname" . }}-metrics"} == 0
    #    for: 2m
    #    labels:
    #      severity: error
    #    annotations:
    #      summary: Redis(TM) instance {{ "{{ $instance }}" }} down
    #      description: Redis(TM) instance {{ "{{ $instance }}" }} is down.
    #  - alert: RedisMemoryHigh
    #    expr: >
    #       redis_memory_used_bytes{service="{{ template "common.names.fullname" . }}-metrics"} * 100
    #       /
    #       redis_memory_max_bytes{service="{{ template "common.names.fullname" . }}-metrics"}
    #       > 90
    #    for: 2m
    #    labels:
    #      severity: error
    #    annotations:
    #      summary: Redis(TM) instance {{ "{{ $instance }}" }} is using too much memory
    #      description: Redis(TM) instance {{ "{{ $instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
    #  - alert: RedisKeyEviction
    #    expr: increase(redis_evicted_keys_total{service="{{ template "common.names.fullname" . }}-metrics"}[5m]) > 0
    #    for: 1s
    #    labels:
    #      severity: error
    #    annotations:
    #      summary: Redis(TM) instance {{ "{{ $instance }}" }} has evicted keys
    #      description: Redis(TM) instance {{ "{{ $instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
