

skindURL: https://minotar.net/skin/

image:
  repository: minotar/processd
  tag: master-939a787
  #pullPolicy: IfNotPresent
  pullPolicy: Always

restartPolicy: Always

## Additional imgd container environment variables
## For instance to add a http_proxy
##
## extraEnv:
##   HTTP_PROXY: "http://superproxy.com:3128"
##   NO_PROXY: "localhost,127.0.0.1"
extraEnv: {}

## Enable pod security policy
pspEnabled: false

strategy:
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 1
  type: RollingUpdate

## User to run processd container as
runAsUser: 10001
readOnlyRootFilesystem: true
runAsNonRoot: true


livenessProbe:
  httpGet:
    path: /healthcheck
    port: http

readinessProbe:
  httpGet:
    path: /healthcheck
    port: http


resources:
#  limits:
#    cpu: 600m
#    memory: 50Mi
  requests:
    cpu: 100m
    memory: 20Mi


service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 80

containerPort: 8080

ingress:
  enabled: false
  annotations: {}
  labels: {}
  className: ""

  host: processd.local
  # Defaults to the processd service, but can accomadate another caching service
  serviceName: ""
  servicePort: ""
  paths:
    - /avatar
    - /helm
    - /cube
    - /cubehelm
    - /bust
    - /body
    - /armor/bust
    - /armour/bust
    - /armor/body
    - /armour/body

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  annotations: {}

podAnnotations: {}

pod:
  labels: {}

replicas: 3

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: false

  selector:
    release: kube-prometheus-stack
  additionalMetricsRelabels: {}
  interval: 30s
  scrapeTimeout: 10s
  ## scheme: HTTP scheme to use for scraping. Can be used with `tlsConfig` for example if using istio mTLS.
  scheme: http
  ## tlsConfig: TLS configuration to use when scraping the endpoint. For example if using istio mTLS.
  ## Of type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig
  tlsConfig: {}
  bearerTokenFile:

## Custom PrometheusRules to be defined
## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
prometheusRule:
  enabled: false
  additionalLabels: {}
  namespace: ""
  rules: []

## Network policy for chart
networkPolicy:
  # Enable network policy and allow access from anywhere
  enabled: false
  # Limit access only from monitoring namespace
  # Before setting this value to true, you must add the name=monitoring label to the monitoring namespace
  # Network Policy uses label filtering
  allowMonitoringNamespace: false
