{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "minotar-skind.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-skind.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-skind.chart" . }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
            {{- $serviceName := .Values.ingress.serviceName | default (include "minotar-skind.fullname" .) -}}
            {{- $servicePort := .Values.ingress.servicePort | default .Values.service.port -}}

            {{- range $path := $.Values.ingress.paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- end }}
{{- end }}
