{{- if .Values.pspEnabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "minotar-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-website.chart" . }}
  name: {{ template "minotar-website.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "minotar-website.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "minotar-website.serviceAccountName" . }}
{{- end -}}
