{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "minotar-imgd.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-imgd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-imgd.chart" . }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end -}}
