apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "minotar-imgd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-imgd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-imgd.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minotar-imgd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ template "minotar-imgd.fullname" . }}-headless
  updateStrategy:
  {{- toYaml .Values.updateStrategy | nindent 4 }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "minotar-imgd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "minotar-imgd.chart" . }}
        {{- if .Values.pod.labels }}
{{ toYaml .Values.pod.labels | indent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "minotar-imgd.serviceAccountName" . }}

      restartPolicy: {{ .Values.restartPolicy }}

      {{- if .Values.antiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "minotar-imgd.name" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
      {{- end }}

      containers:
        - name: imgd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --server.http-listen-port={{ .Values.containerPort }}
          - --cache.uuid.bolt-path=/skind/bolt_cache_uuid.db
          - --cache.userdata.bolt-path=/skind/bolt_cache_usertdata.db
          - --cache.textures.bolt-path=/skind/bolt_cache_textures.db
          - --mcclient.useragent={{ .Values.mcclient.userAgent }}
          - --mcclient.sessionserver-url={{ .Values.mcclient.sessionServerURL }}
          - --mcclient.profile-url={{ .Values.mcclient.profileURL }}

          securityContext:
            readOnlyRootFilesystem: {{ .Values.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.runAsNonRoot  }}
            runAsUser: {{ .Values.runAsUser }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          livenessProbe:
            {{- toYaml .Values.livenessProbe | trim | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | trim | nindent 12 }}
          volumeMounts:
          - mountPath: "/imgd"
            name: bolt-cache-pvc

      initContainers:
        - name: imgd-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/imgd"]
          volumeMounts:
          - name: bolt-cache-pvc
            mountPath: /imgd

  volumeClaimTemplates:
  - metadata:
      name: bolt-cache-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage
