apiVersion: v1
description: Caddy
name: minotar-caddy
version: 1.0.0
appVersion: 1.0.0
home: https://caddyserver.com/
sources:
  - https://github.com/minotar/imgd
keywords:
  - minotar
maintainers:
  - name: LukeH
