{{- range $recordSet := .Values.nodeDNSRecordSets }}
---
apiVersion: flipop.digitalocean.com/v1alpha1
kind: NodeDNSRecordSet
metadata:
  name: {{ $recordSet.name }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" $ }}
spec:
  dnsRecordSet:
{{ toYaml $recordSet.dnsRecordSet | indent 4 }}
  match:
{{ toYaml $recordSet.match | indent 4 }}
{{- end }}
