{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "minotar-flipop.fullname" $ }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" $ }}
    {{- if $.Values.podMonitor.selector }}
    {{- toYaml ($.Values.podMonitor.selector) | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: {{ $.Values.podMonitor.portName }}
    interval: {{ $.Values.podMonitor.interval }}
    scrapeTimeout: {{ $.Values.podMonitor.scrapeTimeout }}
    {{- if $.Values.podMonitor.additionalMetricsRelabels }}
    metricRelabelings:
        {{- range $targetLabel, $replacement := $.Values.podMonitor.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
    {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minotar-flipop.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
