apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" . }}
  name: {{ template "minotar-flipop.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["flipop.digitalocean.com"]
  resources: ["nodednsrecordsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["flipop.digitalocean.com"]
  resources: ["floatingippools", "floatingippools/status", "nodednsrecordsets/status"]
  verbs: ["get", "watch", "list", "update"]

---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" . }}
  name: {{ template "minotar-flipop.fullname" . }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  resourceNames: ["floating-ip-pool-controller-leader-election"]
  verbs: ["get", "update", "patch"]

---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" . }}
  name: {{ template "minotar-flipop.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "minotar-flipop.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "minotar-flipop.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}

---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" . }}
  name: {{ template "minotar-flipop.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "minotar-flipop.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "minotar-flipop.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
