apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "minotar-flipop.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-flipop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-flipop.chart" . }}
