---

grafana_version: "8.2.2"
grafana_conf_dir: "/etc/grafana"

local_bin_path: "/usr/local/bin"

prometheus_service_name: prometheus
prometheus_user_name: prometheus
prometheus_group_name: prometheus
prometheus_version: "2.30.3"
prometheus_force_install: false

blackbox_exporter_service_name: blackbox_exporter
blackbox_exporter_user_name: blackbox_exporter
blackbox_exporter_group_name: blackbox_exporter
blackbox_exporter_version: "0.19.0"
blackbox_exporter_force_install: false
