
- name: set hostnames
  hosts: all
  roles:
    - hostname

- name: monitoring server
  hosts: monitoring
  roles:
    - caddy
    - monitor

- name: monitoring clients
  hosts: all
  roles:
    - prometheus-node-exporter
