{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "minotar-processd.fullname" $ }}
  labels:
    app.kubernetes.io/name: {{ include "minotar-processd.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "minotar-processd.chart" $ }}
    {{- if $.Values.serviceMonitor.selector }}
    {{- toYaml ($.Values.serviceMonitor.selector) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: {{ $.Values.serviceMonitor.scheme }}
    {{- if $.Values.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ $.Values.serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if $.Values.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml $.Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    {{- if $.Values.serviceMonitor.additionalMetricsRelabels }}
    metricRelabelings:
        {{- range $targetLabel, $replacement := $.Values.serviceMonitor.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
    {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minotar-processd.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end }}
