
pspEnabled: false


ingress:
  enabled: true
  className: nginx
  host: minotar.net
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"

resources:
  limits:
    cpu: 50m
    memory: 30Mi
