
floatingIpPools:
  # Primary source of inbound traffic from Cloudflare on HTTP/S (Firewalled)
  - name: ingress-ip-pool
    provider: digitalocean
    region: nyc1
    # 2 IPs "balances" inbound traffic
    desiredIps: 2
    ips:
      - 138.197.227.6
      - 137.184.240.71
    dnsRecordSet:
      recordName: ingress
      zone: cluster.minotar.net
      ttl: 30
      provider: digitalocean
    match:
      nodeLabel: doks.digitalocean.com/node-pool=minotar-pool
      podLabel: app.kubernetes.io/name=ingress-nginx,app.kubernetes.io/component=controller
      podNamespace: nginx-ingress


nodeDNSRecordSets:
  # All nodes
  - name: k8-record-set
    dnsRecordSet:
      recordName: k8
      zone: cluster.minotar.net
      ttl: 30
      provider: digitalocean
    match:
      nodeLabel: doks.digitalocean.com/node-pool=minotar-pool
  # Ensures the external monitoring can use a single address for metric grabbing
  - name: metrics-record-set
    dnsRecordSet:
      recordName: metrics
      zone: cluster.minotar.net
      ttl: 30
      provider: digitalocean
    match:
      nodeLabel: doks.digitalocean.com/node-pool=minotar-pool
      podLabel: app=prometheus,app.kubernetes.io/name=prometheus,prometheus=kube-prometheus-stack-prometheus
      podNamespace: kube-prometheus-stack

podMonitor:
  enabled: true
  selector:
    release: kube-prometheus-stack
