

skindURL: http://frontend-varnish-httpcache/skin/

pspEnabled: false


ingress:
  enabled: true
  className: nginx
  host: minotar.net
  serviceName: frontend-varnish-httpcache
  servicePort: 80

resources:
  limits:
    cpu: 200m
    memory: 100Mi

serviceMonitor:
  enabled: true
  interval: 5s
  scrapeTimeout: 5s
