
resources:
  limits:
    memory: 1500Mi
  requests:
    memory: 1200Mi

pspEnabled: false


ingress:
  enabled: true
  className: nginx
  host: minotar.net
  serviceName: frontend-varnish-httpcache
  servicePort: 80

serviceMonitor:
  enabled: true
  interval: 5s
  scrapeTimeout: 5s
