
mcclient:
  userAgent: minotar/imgd (https://github.com/minotar/imgd) - k8
  sessionServerURL: https://sessionserver.mojang.com/session/minecraft/profile/
  profileURL: https://api.mojang.com/users/profiles/minecraft/


resources:
  limits:
    memory: 500Mi

pspEnabled: false


serviceMonitor:
  enabled: false
