{{- if .Values.pspEnabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ include "minotar-caddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minotar-caddy.chart" . }}
  name: {{ template "minotar-caddy.fullname" . }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "minotar-caddy.fullname" . }}-psp
    verbs:
    - use
{{- end -}}
